name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup Buildozer
      uses: ckulka/setup-buildozer@v1.5.0
      with:
        buildozer-version: latest
        # Install Android SDK
        android-api: 30
        android-build-tools: '30.0.3'
        android-ndk: '25.1.8937393'
        # Optional: kivy
        python-version: '3.9'

    - name: Install Cython (required for Kivy)
      run: |
        pip install Cython==0.29.33

    - name: Run Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "Error: buildozer.spec not found!"
          exit 1
        fi
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        path: bin/*.apk
        if-no-files-found: error
        retention-days: 7

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(grep -E "^version" buildozer.spec | cut -d'=' -f2 | xargs)
        TAG="v$VERSION"
        gh release delete "$TAG" --yes || true
        gh release create "$TAG" \
          --title "Release $VERSION" \
          --notes "Auto-built APK from GitHub Actions" \
          bin/*.apk
