name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libmtdev-dev libxcursor-dev libxinerama-dev libxrandr-dev libxss-dev libgtk-3-dev libjpeg-dev libtiff-dev libopenjp2-7-dev libharfbuzz-dev libfribidi-dev libxcb1-dev libegl1-mesa-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Run Buildozer
      run: |
        buildozer init || true
        # Pastikan buildozer.spec sudah ada
        if [ ! -f buildozer.spec ]; then
          echo "Error: buildozer.spec not found!"
          exit 1
        fi
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        path: bin/*.apk
        if-no-files-found: error
        retention-days: 7

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(grep -E "^version" buildozer.spec | cut -d'=' -f2 | xargs)
        TAG="v$VERSION"
        gh release delete "$TAG" --yes || true
        gh release create "$TAG" \
          --title "Release $VERSION" \
          --notes "Auto-built APK from GitHub Actions" \
          bin/*.apk
